version: '3'

services:
    hts-embeddings:
        image: hts-embeddings
        volumes:
            - ./src:/root/src
            - ./notebooks:/root/notebooks
            - ./data:/root/data
        command: python experiment.py reproduce